name: CLion
files:
  - Library/Application Support/JetBrains/CLion2025.3/codestyles
  - Library/Application Support/JetBrains/CLion2025.3/keymaps
  - Library/Application Support/JetBrains/CLion2025.3/tools
  - Library/Application Support/JetBrains/CLion2025.3/options
  - Library/Application Support/JetBrains/CLion2025.3/colors
  - Library/Application Support/JetBrains/CLion2025.3/clion.vmoptions
