name: DataGrip
files:
  - Library/Application Support/JetBrains/DataGrip2025.3/codestyles
  - Library/Application Support/JetBrains/DataGrip2025.3/keymaps
  - Library/Application Support/JetBrains/DataGrip2025.3/tools
  - Library/Application Support/JetBrains/DataGrip2025.3/options
  - Library/Application Support/JetBrains/DataGrip2025.3/colors
  - Library/Application Support/JetBrains/DataGrip2025.3/datagrip.vmoptions
  - Library/Application Support/JetBrains/DataGrip2025.4/codestyles
  - Library/Application Support/JetBrains/DataGrip2025.4/keymaps
  - Library/Application Support/JetBrains/DataGrip2025.4/tools
  - Library/Application Support/JetBrains/DataGrip2025.4/options
  - Library/Application Support/JetBrains/DataGrip2025.4/colors
  - Library/Application Support/JetBrains/DataGrip2025.4/datagrip.vmoptions
  - Library/Application Support/JetBrains/DataGrip2026.1/codestyles
  - Library/Application Support/JetBrains/DataGrip2026.1/keymaps
  - Library/Application Support/JetBrains/DataGrip2026.1/tools
  - Library/Application Support/JetBrains/DataGrip2026.1/options
  - Library/Application Support/JetBrains/DataGrip2026.1/colors
  - Library/Application Support/JetBrains/DataGrip2026.1/datagrip.vmoptions
