name: Visual Studio Code Insiders
files:
  - Library/Application Support/Code - Insiders/User/snippets
  - Library/Application Support/Code - Insiders/User/prompts
  - Library/Application Support/Code - Insiders/User/keybindings.json
  - Library/Application Support/Code - Insiders/User/settings.json
